# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Reuben Smit
email: "&#x72;&#101;&#117;&#98;&#x69;&#120;&#46;&#115;&#x6D;&#x69;&#116; [at] &#x67;&#109;&#97;&#x69;&#108; [dot] &#x63;&#111;&#x6D;"
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.rsmit.co.za" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  Reubix29
# linkedin_username: kamperh
google_scholar: https://scholar.google.com/citations?hl=en&user=7kHu-SoAAAAJ

# Icon versions
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="  

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
